### ISSUE TITLE
Cannot fit bootloader in flash

### ISSUE THREAD

**Issue by jchatt0** [usedbytes/rp2040-serial-bootloader#11] opened 2024-03-23 15:39 UTC
Cloned the repo, ran CMAKE without any changes, and I get this error: 
[build] c:/progra~1/raspbe~1/picosd~1.1/gcc-ar~1/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld.exe: bootloader.elf section `.text' will not fit in region `FLASH'
[build] c:/progra~1/raspbe~1/picosd~1.1/gcc-ar~1/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld.exe: region `FLASH' overflowed by 10608 bytes

**Comment by usedbytes** [comment] 2024-03-23 15:43
Duplicate of #1 and #7

**Closed as completed by usedbytes** 2024-03-23 15:43 UTC
